# Settings for LPJmL specifically for coupling (pycoupler)
#   (not covered by LPJmL's direct config)
lpjml_settings:
    country_code_to_name: true
    iso_country_code: true

# Variables to be written to copan_core_data table file 
output:
    individual:
        - "aft_id"
        - "behaviour"
        - "tpb"
        - "pbc"
        - "social_norm"
        - "attitude"
        - "attitude_own_land"
        - "attitude_social_learning"
        - "soilc"
        - "cropyield"

# Define how copan_core_data table file should be written
output_settings:
    write_lon_lat: true
    format: "csv"

# Define which individual variables map with coupled LPJmL input variables
coupling_map:
    behaviour: ["with_tillage"]  # "residue_on_field"

control_run: False
pioneer_share: 0.25

# Analogous to LPJmL pftpar, define the AFT parameters for the two different
#   farmer types
aftpar:
    # AFT for conservative/traditional values following farmer tending to stay
    #   with conventional agriculture
    traditionalist:
        pbc: 0.95
        weight_attitude: 0.6
        weight_yield: 0.8
        weight_soil: 0.4
        weight_norm: 0.4
        weight_social_learning: 0.4
        weight_own_land: 0.6
        # duration of waiting time before switching to another strategy
        strategy_switch_duration: 10 # years

    # AFT for pioneer farmer who more likely tends to switch to new (promising)
    #   regenerative agriculture practices
    pioneer:
        pbc: 0.75
        weight_attitude: 0.8
        weight_yield: 0.4
        weight_soil: 0.8
        weight_norm: 0.2
        weight_social_learning: 0.6
        weight_own_land: 0.4
        # duration of waiting time before switching to another strategy
        strategy_switch_duration: 10 # years
